### PR TITLE
Fix workflow triggers

### PR DESCRIPTION
**Pull request by grevend**
Signed-off-by: David Greven <opensource@grevend.dev>

### CODE REVIEW

**Review by strieflin — APPROVED** [review]
LGTM

**Comment by strieflin** [comment]
Maven servers should be defined as follows:

```yaml
servers: |
  [{
    "id": "github",
    "username": "${{ github.actor }}",
    "password": "${{ secrets.GITHUB_TOKEN }}"
}]
```

See https://github.com/carbynestack/castor/blob/79c4e2304af30f63161448802ebcd4e15cc2ed35/.github/workflows/build-test-deploy.yaml#L31-L36.

**Comment by strieflin** [comment]
Your commits are not signed.

**Comment by grevend** [comment]
> Your commits are not signed.

Fixed the server secrets and resigned my commits.

**Review by strieflin — COMMENTED** [review]
LGTM

**Review by strieflin — APPROVED** [review]

**Pull request merged**
