### PR TITLE
Embrace Given-When-Then (GWT) test naming

### PR DESCRIPTION
**Pull request by grevend**
Signed-off-by: David Greven <opensource@grevend.dev>

### CODE REVIEW

**Review by strieflin — APPROVED** [review]
LGTM

**Review by strieflin — CHANGES_REQUESTED** [review]
Some commits are not signed.

**Comment by grevend** [comment]
> Some commits are not signed.

I re-signed and squashed my commits.

**Comment by strieflin** [comment]
Hi David, there is a conflict to be resolved before we can merge this PR.

**Review by strieflin — APPROVED** [review]
LGTM

**Pull request merged**
